### ISSUE TITLE
[Warnsys] Updated `get_mute_role` in cache

### ISSUE THREAD

**Issue by Drapersniper** [retke/Laggrons-Dumb-Cogs#103]
Sorry for removing the template, making this issue so that i dont forget to follow up with a PR for you.

```py
    async def get_mute_role(self, guild: discord.Guild):
        role_id = self.mute_roles.get(guild.id, False)
        if role_id is not False:
            return role_id
        role_id = await self.data.guild(guild).mute_role()
        if role_id:
            self.mute_roles[guild.id] = role_id
        return role_id
```
Needs to account for servers that do not haver a mute role to avoid calling config every time for those.
Need to also ensure the cache is updated when a mute role is added.

**Comment by laggron42** [comment]
The cache is already updated when a mute role is modified or set.

Here when a mute role is specified:
https://github.com/retke/Laggrons-Dumb-Cogs/blob/96f6da54eb44cbcbb8ad3c2c30cb02c783da6d93/warnsystem/settings.py#L523

And here when the role is created by the bot:
https://github.com/retke/Laggrons-Dumb-Cogs/blob/96f6da54eb44cbcbb8ad3c2c30cb02c783da6d93/warnsystem/api.py#L764

I tried improving performances by setting the default result of `dict.get` to `False` instead of `None`, to make a difference between not set and not found in cache, but I guess it doesn't work as I intended...

Also it's fine for the template, outdated anyway lol

**Comment by Drapersniper** [comment]
The issue here is that when there is no `mute_role()` set this is not cached. which means its called on every member_update for every server that doesn't have it set. and always returrns None.

In other words it is only cached, if the `mute_role` has been set.

**Comment by laggron42** [comment]
https://github.com/retke/Laggrons-Dumb-Cogs/blob/cd49919e6beddf89317ea927fd1d0b93b6f00332/warnsystem/cache.py#L57-L64

I understand there is an issue with that, and I agree this needs to be resolved. I'm just trying to understand why it's happening.

By using `False` as the default return value when nothing is found, I am certain the guild is not in the cache. 
```py
role_id = await self.data.guild(guild).mute_role() 
if role_id: 
    self.mute_roles[guild.id] = role_id 
```
At this point, let's suppose the mute role isn't set, it should set `None` inside the cache. Then once the mute role is fetched later, `None` is returned, not `False`, making the function return the value.

This is what I had in mind when coding, and I really don't know why it's actually calling config when there's nothing set.
