### ISSUE TITLE
[Warnsystem] Any mod is able to clear the entire modlog

### ISSUE THREAD

**Issue by Skyridr** [retke/Laggrons-Dumb-Cogs#151]
It appears that any moderator can clear the entire modlog, is there anyway this can be adjusted so only admins+ (or specific users) can remove everyone's warnings?

**Comment by laggron42** [comment]
Kinda complex since a single command groups viewing, editing and deleting, so permissions can't be used for that ; and redefining who should be a mod or not based on roles and specific users feels too much for that.

Probably will stay the way it is unless I rewrite that command, or find a "light" solution
