### ISSUE TITLE
[V3 say] Edit sent messages

### ISSUE THREAD

**Issue by HelmicNewciv** [retke/Laggrons-Dumb-Cogs#43]
# Feature request

Cog: Say

## Description
It'd be useful to have a way to edit messages sent with !say.  It'd allow for things like a rules post or a message listing out all the roles you can join to be editable by all admins/mods, without requiring the whole channel be deleted and re-posted.

Wouldn't want it to edit any message the bot has sent, though, to avoid shenanigans with stuff like editing modlogs.

**Comment by retke** [comment]
This would require to store literally every message sent by the bot, while Say currently doesn't have anything to store, and if it's added, the old messages won't be editable because of this. This can also be a problem for some people since it can take a lot of memory.

If this is added, this should either allow all edits or be optional. Needs more discussion about this.

**Comment by NeuroAssassin** [comment]
You could also store the message IDs, and then with an edit command, first make sure that the message ID is stored, and carry it out from there maybe?

**Comment by HelmicNewciv** [comment]
I imagine most servers aren't using !say so often that storing the message ID's would be a serious issue.  !sayedit might be a way to explicitly flag that this particular message should be editable if the general rule is that messages shouldn't be edited, which would at least make it possible for a mod team to collectively edit things like rules or role reaction lists.

**Comment by Dezyox** [comment]
You can use `Editor` cog from `Toxic-Cogs`

**Comment by laggron42** [comment]
I'll consider this resolved as 3rd party cogs allows you to do this, see the comment above.
