### ISSUE TITLE
warnlist shows all left members as "Unknown#0000"

### ISSUE THREAD

**Issue by Skyridr** [retke/Laggrons-Dumb-Cogs#81]
I noticed that all left members are shown as  Unknown#0000:

> --- Case 79 ---
> Member:    Unknown#0000 (ID: 576579935074910208)
> Level:     3
> Reason:    Stop spamming...
> Author:    Skyrider#1337 (ID: 133631162894516225)
> Date:      2020-06-08 07:49:18

When sometimes the userID can be converted back to the username, though not always. But if a  userid to user/nickname would fail, is it possible that there can be an extra row in the data so the name is used?

EG:

>                      "level":3,
>                      "author":133631162894516225,
>                      "nickname: Hello!!"
>                      "reason":"Stop spamming...",
>                      "time":"1591595358",
>                      "duration":null,
>                      "until":null,
>                      "roles":[
> 
>                      ]

So we can actually see who the user "was" before he/she was booted (or left) the server.

**Comment by Skyridr** [comment]
Same would apply when using the [p]warnings USERID command, also shows Unknown#0000.

Would be nice to know their last known user/nickname when a warn command is issues on them.

**Comment by laggron42** [comment]
The fact that WarnSystem doesn't show the username is intended. Discord allows bots to get data from a user ID, but the endpoint is under a large cooldown, and caused issues. I decided to remove all usage of this endpoint for version 1.2 to prevent those issues.

Storing the member's name on warn would be pretty heavy, due to the potential name changes and additional data. However, the core mod cog already does the job of saving previous names and nicknames, an interface could be made with this, using the last known name, but it doesn't save anything if the name is not updated, so that wouldn't be very efficient for most cases.

WarnSystem is already a very heavy cog, and I'm not a fan of names management to be honest, that can cost a lot of performances, especially since the event `on_member_update` is one of the most called ones on a bot. Fortnite's mod team (also using Red) had issues with core mod for that. My recommandation for now is to ask for the `[p]names`/`[p]userinfo` commands from mod to be usable with an ID.
